### ISSUE TITLE
Implement a Settings panel

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#101]
Problem description:

1. The "General" tab now has options for defining a tile cache path and time limit. They behave like the other fields, so they are empty after each start. The path and time limit of the cache have to be specified again and again.
2. The tile cache path and time limit are the only two options, that do not relate to the animation. They do something different, they specify the behavior of GPX Animator. And they should be permanent and not forget their settings.

Solution 1:
- Rename the "General" tab to "Animation".
- Create a new "Settings" tab in front of the "Animation" tab.
- Move the two fields "Tile Cache Directory" and "Tile Cache Time Limit" to the "Settings" tab.
- Make the "General" tab the default tab.
- Make the settings permanent (saving and loading).

Solution 2:
- Create a settings dialog.
- Add a menu entry opening the settings dialog.
- Move the two fields "Tile Cache Directory" and "Tile Cache Time Limit" to the settings dialog.
- Make the settings permanent (saving and loading).

@zdila and @n76, what do you think about this idea?

**Comment by n76** [comment]
Either of these would be a good idea.

**Comment by n76** [comment]
Maybe it ought to be a "defaults" rather than settings. For example, I almost always want to create an animation that can be edited into a larger video. So I always set the width and height values. At present I am also using 30 FPS which is a default but I can see in the future I might want to default to some other rate.

Maybe some way, preference or settings could be used to save a larger set of defaults than just the tile cache configuration.

**Comment by zdila** [comment]
@McPringle I like the 2nd solution a slightly more.

**Comment by McPringle** [comment]
@n76: You made me think of an additional feature: #103 

@zdila: For me, the 2nd solution feels more natural and we could use a settings framework, which handles the saving and loading and creates a UI panel on demand. Let's do this! :-)

**Comment by McPringle** [comment]
The default storage for the settings should be the `$HOME/.gpx-animator` directory. A hidden directory in the home folder. Using the system properties, this should work on all operating systems like Linux, Mac OS, Windows...

**Comment by McPringle** [comment]
We should use the Preferences API of Java:
https://docs.oracle.com/javase/8/docs/technotes/guides/preferences/overview.html
