### ISSUE TITLE
Save as Default

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#103]
The default values for all settings after application startup are hardcoded. It should be possible to save the settings from the "General" tab as a default. That would make it much easier for some people because I always render all my animations with the same size (4K) and frame rate (60) and I don't like to enter my preferred values after each start. And I don't want to use save and load because I could accidentally overwrite the loaded file when I alter these settings,

Additional feature: Reset Defaults to Factory Settings

**Comment by rindy22** [comment]
Hi, I will try to resolve this issue if it is still free.

**Comment by McPringle** [comment]
Hi @rindy22, go for it! I'll set the status of this issue to "in progress", so nobody else will grab it.
