### ISSUE TITLE
Make Flashback Color configurable

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#104]
The configuration option is already available in `Option.java`.

**Comment by Jman24** [comment]
Hello, I would like to work on this if it's still available. Thanks!

**Comment by McPringle** [comment]
Sure, you are welcome! Thank you very much for your interest. I’ll tag this issue as “in progress”, so others know you are working on it.

**Comment by Jman24** [comment]
Could you please provide more specifics on this issue? It looks to me like the flashback color is already configurable as it is present in GeneralSettingsPanel.java and in Renderer.java. Thanks.

**Comment by McPringle** [comment]
Crazy. I have to analyze the code and identify what is missing.

**Comment by McPringle** [comment]
Yes, @Jman24, someone implemented this already and forgot to close the issue. Sorry for that!
