### ISSUE TITLE
Max/Min Long Spinner Limits

### ISSUE THREAD

**Issue by bat-bloke** [zdila/gpx-animator#107]
The max/min spinner range is currently set to 0 to 180 for longitude. I believe this should be -180 to +180?

I think the GeneralSettingsPanel class lines 242 and 295 need to be updated. (as below)

maxLonSpinner.setModel(new EmptyNullSpinnerModel(null, Double.valueOf(-180.0), Double.valueOf(180.0), Double.valueOf(0.1), false));

though I am not 100% as I can't seem to package the edited version and test (issues with my version of eclipse). I will update if I have success

**Comment by McPringle** [comment]
If you want to create the artifact to run GPX Animator, you can do that very easy at the command line:

- Linux & Mac: `./mvnw package`
- Windows: `mvnw package`

You'll find the artefact in the `target` directory. If you get an error complaining about the `--release` flag, just remove the line 24 from the `pom.xml`.

**Comment by bat-bloke** [comment]
I have now tried this and I am getting compilation errors on RendererTest
ln35, thus the build fails.
Any ideas?

**Comment by McPringle** [comment]
Yes, yesterday evening I had similar problems. Looks like this is a side effect of adding the `Manifold` compiler plugin with PR #54 a few days ago. I opened issue #108 which has the same cause (the error message depends on the Java version).

You could just delete the test to successfully compile the artifact. Maybe you have to remove all `Manifold` dependencies from the `pom.xml`, too. Sorry for the inconvinience!

**Comment by bat-bloke** [comment]
Manage to get it to compile and run.
Now can't seem to actually use the lat/long limits without errors.
I also seem to only be able to have bicycle icons!? Not quite sure why
that's changed

**Comment by McPringle** [comment]
The bicycle icon is a new feature (issue #54) which is still work in progress. It will be configurable, soon. If you need help regarding your errors, please feel free to discuss it here.

**Comment by bat-bloke** [comment]
Okay I thought I'd seen it mentioned before!
Error -411648 is what I get when trying to constrain the boundary box
[image: image.png]

**Comment by bat-bloke** [comment]
Spinner limit fixed, pull request made.
Worth noting that the sizing, zoom, and centering of the map will need addressing as this has to be manually set by trial and error when bounding box is set
