### ISSUE TITLE
Create a new application icon

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#111]
The actual icon is not very nice. Could be better... :-)

Edit: The Icon must be available in the following sizes:
- 16x16
- 32x32
- 48x48
- 128x128

**Comment by heroichornet** [comment]
something like this? ![GPXLOGO](https://user-images.githubusercontent.com/1138612/71040933-169cba80-2128-11ea-8389-4f5a1c2ecc0c.png)

**Comment by zdila** [comment]
![ga](https://user-images.githubusercontent.com/636095/71064462-6eaadf80-216f-11ea-9f9e-b8e8a6e19cd0.png)

[ga.svg.gz](https://github.com/zdila/gpx-animator/files/3977136/ga.svg.gz)

**Comment by heroichornet** [comment]
@zdila ok maybe if we merge the two ideas? I like the idea of the film strip but I would round the edges and add a little more modern touch by maybe making the font white and the background dark red?

**Comment by zdila** [comment]
ok, try :-)

**Comment by McPringle** [comment]
In my opinion, the icon should be square

**Comment by heroichornet** [comment]
![rect2836](https://user-images.githubusercontent.com/1138612/71203146-c34c7880-229d-11ea-8781-e8bba0043226.png)

**Comment by heroichornet** [comment]
![icon_32](https://user-images.githubusercontent.com/1138612/71356614-0d29ad00-2583-11ea-960b-1dc2f59fbe88.png)
![icon_48](https://user-images.githubusercontent.com/1138612/71356615-0d29ad00-2583-11ea-8d0e-8b62e7a499d8.png)
![icon_128](https://user-images.githubusercontent.com/1138612/71356616-0dc24380-2583-11ea-9a85-9e17b81149d7.png)
![icon_16](https://user-images.githubusercontent.com/1138612/71356617-0dc24380-2583-11ea-8aee-35cc6221f6dd.png)

**Comment by heroichornet** [comment]
![gpx_animator_banner](https://user-images.githubusercontent.com/1138612/71362906-bf6b6f80-2597-11ea-9ba2-d1487258c859.png)
![icon_16](https://user-images.githubusercontent.com/1138612/71362907-bf6b6f80-2597-11ea-92d1-221e96b8e98f.png)
![icon_32](https://user-images.githubusercontent.com/1138612/71362908-bf6b6f80-2597-11ea-9a55-75ceb081e67a.png)
![icon_48](https://user-images.githubusercontent.com/1138612/71362909-bf6b6f80-2597-11ea-9910-a144425fbbc5.png)
![icon_128](https://user-images.githubusercontent.com/1138612/71362910-bf6b6f80-2597-11ea-91c1-42baf2e4b34e.png)

**Comment by heroichornet** [comment]
![icon_128](https://user-images.githubusercontent.com/1138612/71363388-3f460980-2599-11ea-8116-e48e6583de73.png)

**Comment by McPringle** [comment]
Brainstorming Hackergarten Luzern:
![Image](https://i.imgur.com/3xUAI2x.jpg)

**Comment by Interactiondesigner** [comment]
Here we go ... Icons, File icons and Splash 
![GPXA_App_16](https://user-images.githubusercontent.com/17220369/86405806-4b322700-bcb2-11ea-9b8d-f37dd2cf6630.png)
![GPXA_App_32](https://user-images.githubusercontent.com/17220369/86405808-4b322700-bcb2-11ea-9e86-7a0778c8dfed.png)
![GPXA_App_48](https://user-images.githubusercontent.com/17220369/86405809-4bcabd80-bcb2-11ea-83e8-1674c73b194b.png)
![GPXA_App_128](https://user-images.githubusercontent.com/17220369/86405811-4bcabd80-bcb2-11ea-8e9d-ae8cc2559819.png)
![GPXA_File_16](https://user-images.githubusercontent.com/17220369/86405812-4c635400-bcb2-11ea-94d2-e7bf75fa7210.png)
![GPXA_File_32](https://user-images.githubusercontent.com/17220369/86405816-4cfbea80-bcb2-11ea-82bf-6ab7e1f982e9.png)
![GPXA_File_48](https://user-images.githubusercontent.com/17220369/86405817-4cfbea80-bcb2-11ea-90c8-03f8ae4a16fc.png)
![GPXA_File_128](https://user-images.githubusercontent.com/17220369/86405819-4cfbea80-bcb2-11ea-9766-a22e23003769.png)
![GPXA_Splash@1](https://user-images.githubusercontent.com/17220369/86405822-4d948100-bcb2-11ea-98c4-1fef89be632f.png)
![GPXA_Splash@2](https://user-images.githubusercontent.com/17220369/86405826-4e2d1780-bcb2-11ea-9772-da7f2aaa1019.png)









Screen

**Comment by maebli** [comment]
![60F59A36-0416-4CA6-BB20-C773802795E7](https://user-images.githubusercontent.com/1138612/128594373-6095d54d-e1ea-43fe-86ec-c282be392bd7.jpeg)

sadly I did the design before I realised the issue was already closed. I’m posting it anyways

**Comment by McPringle** [comment]
Nice work, @maebli! But, as you might think, we have already changed the icon and splash screen and don't want to change it again. Thank you very much for your contribution!
