### ISSUE TITLE
Add tail color parameter

### ISSUE THREAD

**Issue by sookoll** [zdila/gpx-animator#14]
Tail color should be changeable. I also notice when set tail length to 0, no marker or label displayed any more.

**Comment by zdila** [comment]
Thanks for the bugreport.

I've fixed the problem with the missing marker. 

About tail color - do you think it should be per track or one global color for all tracks?

**Comment by sookoll** [comment]
Not sure. For me one global color is enough, but there might be other opinions.

**Comment by McPringle** [comment]
Because you can have different colors for different tracks, in my opinion it should be a per track option.
