### ISSUE TITLE
Trim the route to anonymise the point of living

### ISSUE THREAD

**Issue by pschonmann** [zdila/gpx-animator#15]
Ahoj, rád bych se zeptal zda by šlo udělat anonymizovani trasy. Začátek každého gpx by byl zkrácen o nastavenou hodnotu v metrech. Ne každý je řád když vizualizujes kde bydlí ;) Diky

**Comment by zdila** [comment]
Ahoj. Mozem to casom pridat, ale zatial mozes pouzit napr. gpsprune (http://activityworkshop.net/software/gpsprune/) na orezanie GPX.

**Comment by McPringle** [comment]
@pschonmann, I translated the title of your issue (hopefully correctly, I used Google Translate to understand it).
