### ISSUE TITLE
Speed/GPS/time box position

### ISSUE THREAD

**Issue by okievv** [zdila/gpx-animator#153]
When specifying a significant margin, the Speed/GPS/time box appears amid the video.
[tweak-margin.zip](https://github.com/zdila/gpx-animator/files/4007875/tweak-margin.zip)

**Comment by McPringle** [comment]
Good morning @okievv 

I rendered the video with the data you provided and got the expected result:

![grafik](https://user-images.githubusercontent.com/1254039/71573829-11574c80-2ae6-11ea-9a44-77543c824544.png)

You entered a margin of 100 and the box positions are respecting the margin. Does it look different on your system?

**Comment by okievv** [comment]
Indeed, that's what I also got. I used (maybe: abused) the 'margin' to zoom out the background map, because I can't work with the bounding box. Another advantage would be that the 'margin' zoom out works relatively, 
I assumed that the margin would only affect the map rather than other things like the speed box. Surely, it's a philosophy how to consider.
Besides, 'zoom' also impacts the size of the speed box: it can lead from dominating the entire video (zoom=1) to unreadable small (zoom=10).

**Comment by McPringle** [comment]
Well, the margin is supposed to make a space where nothing is shown. That is important if you want to embed this video in another video using video editing software with a custom border.

If the font is too huge or too small, you can change it using the font size feature. Besides that, I entered a new feature request to make the font changeable (#154). Another new feature I was thinking of while testing and rendering your video is the position of the text boxes (#155).

I started refactoring the code of the rendering process (#148) to make it easier to find and fix your bounding box problem (#145).

As the border works as expected, I'll close this issue now.
