### ISSUE TITLE
Create support e-mail address for non-GitHub-users

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#167]
On the website, there is the private email address of @zdila. We have an own domain name so we can create an own support email address which forwards the email to @zdila and @McPringle, so the private email address does not need to be mentioned on the website and it easy possible to extend the range of supporters.

@zdila, what do you think about this idea?

**Comment by zdila** [comment]
Feel free to update e-mail address as you propose. Thanks.
