### ISSUE TITLE
error saving configuration

### ISSUE THREAD

**Issue by danbjoseph** [zdila/gpx-animator#18]
Received an error when trying to save a configuration. It should save the general settings as well as all added tracks and settings? 

![screen shot 2015-09-21 at 11 13 12 am](https://cloud.githubusercontent.com/assets/4806884/9995876/594bfdfa-6052-11e5-88e8-618d49e47d82.png)

Running GpxAnimator-1.2.3.jar on OS X Yosemite 10.10.4 with Java 8 Update 51

**Comment by zdila** [comment]
Thanks for the report. Please run GPX Animator from the commandline and paste here the stacktrace when you get this error.

**Comment by pschonmann** [comment]
No stacktrace in stdout. Thats because i wanted debug option in my previous requests :)

**Comment by pschonmann** [comment]
v1.2.0 works fine

**Comment by pschonmann** [comment]
Only when program starts its print
Říj 07, 2015 9:30:47 DOP. java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
But when saving file, no exception in output.
