### ISSUE TITLE
Photos in GPX-Animator

### ISSUE THREAD

**Issue by charlysog** [zdila/gpx-animator#186]
I have been using "GPX-Animator" for a few weeks now (bike routes made with Komoot) and actually also successfully, only I have not yet been able to incorporate photos into the route. The program menu offers me to enter the storage location and the display time of the photos, but I then do not know how to do the placement and insertion of the photos at all. I would be most grateful for any tips.

**Comment by McPringle** [comment]
Sorry for the long delay, I was extremely busy the last weeks and GPX Animator is a hobby project. The photos are placed automatically in the correct position. For this, GPX Animator reads the time the photo was taken from the photo metadata. If the photo has no metadata with the time, GPX Animator can not handle this. Please check the metadata. Smartphones and most cameras write the date and time. Maybe your camera has a wrong date or time set? There is still a lot of improvement in adding photos to the animation.

Btw, today we released v1.5 with a lot of bug fixes and enhancements. You can download it from https://gpx-animator.app/

**Comment by McPringle** [comment]
Hi @charlysog, we found a bug (#195) in GPX Animator v1.4+ which caused errors in the rendering of photos. This bug is fixed in the upcoming v1.5.1 of GPX Animator, which will be available soon.
