### ISSUE TITLE
Commandline doesnt work in 1.4

### ISSUE THREAD

**Issue by waschulte** [zdila/gpx-animator#191]
Having to move up from 1.3 to 1.4 due to a map rendering issue, my scripts don't work anymore. EVen calling GpxNavigator with only one input file leads to a crash with lots of java warnings:
[gpxan.txt](https://github.com/zdila/gpx-animator/files/4836786/gpxan.txt)

The command was:
       java -jar ~/bin/GpxAnimator-1.4.jar --input 2017-11-29.gpx
In 1.3 this works fine.

System:    Host: vivobook-mint19 Kernel: 5.3.0-51-generic x86_64 bits: 64 Desktop: Cinnamon 4.4.8 
           Distro: Linux Mint 19.3 Tricia 
Machine:   Type: Laptop System: ASUSTeK product: VivoBook_ASUSLaptop X580GD_N580GD v: 1.0 
           serial: <root required> 
           Mobo: ASUSTeK model: X580GD v: 1.0 serial: <root required> UEFI: American Megatrends 
           v: X580GD.309 date: 10/18/2018

java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

What am I doing wrong ?

**Comment by McPringle** [comment]
Looks like there is a bug in GPX Animator. From tomorrow on I'm on a long bike packing tour so I can take a look into this when I am back, which is the beginning of August. The bug does not sound very complicated, maybe someone else can take a look earlier.

**Comment by McPringle** [comment]
Btw, today we released v1.5 with a lot of fixes and improvements. You can download it from our official website: https://gpx-animator.app/

**Comment by waschulte** [comment]
Hello McPringle,
Thanks for the reply. I tried 1.5, but it looks like the command-line isn't working there at all !
I use scripts to make sure all parameters for different sessions are the same and to add meaningful labels to every added track. A script makes this much more easy.
In 1.5 though I can't get any parameter being used, not even a GPX file. If I do "gpx-animator --input /mnt/Public/BE-Waimes-apr-2019/GPS/Auto.gpx" it hangs in the splash screen. 

It looks like there is a bit of a problem with command-line usage.

**Comment by McPringle** [comment]
On the command line you still have to use the Java Archive (JAR), not the native executable. The native executable is only a wrapper for the GUI. The JAR file is in the same directory as the native executable file. The bug which caused the command line use to fail is fixed with v1.5.1, which will be available soon.

**Comment by waschulte** [comment]
The normal way for me to start is in a script:
    java -jar ~/bin/GpxAnimator-1.4.jar ${options} ${gpxfiles}
in which options contain what i want for options (if needed also --gui) and gpxfiles is a sequence of "--input <file>".

Thanks for repairing it and iI am looking forward to it.

**Comment by waschulte** [comment]
Just tried it out. Works like a charm !

Many thanks for that.
