### ISSUE TITLE
Pictures not rendered on 1.5

### ISSUE THREAD

**Issue by herrwusel** [zdila/gpx-animator#195]
I tried to render pictures with the new version 1.5 on linux and win10. Both systems ended up with a movie without showing the actual pictures. Same project worked with the previous version. Any one else experienced this?

**Comment by McPringle** [comment]
Sorry for the problem. I am on a bike packing tour and will be back at the end of the month. Then I can hopefully apply a fix for this problem.

**Comment by McPringle** [comment]
Thank you very much for your report. The fix will be included in the next release of GPX Animator (v1.5.1), which will be available soon.
