### ISSUE TITLE
Enhancement: fade-in to new look of the map at the end?

### ISSUE THREAD

**Issue by mnalis** [zdila/gpx-animator#2]
The original party renderer had a beautiful feature that and the end, when all GPX tracks were finished animating, it could fade-in gradually over several seconds to a new picture showing how the map looks after editing.

The feature was great as it showed real progress of the whole process.

So, it first showed old (original) state as the background map (gpx-animator does this), then it showed moving dots leaving trails in different colors (gpx-animator also does this), and the it showed new (current) map (gpx-animator does not yet have this as of 1.0.1).

Obviously, for it gpx-animator would need to have an option to specify another TMS which would be used for final map, and maybe specify how many seconds should an fade-in take.

Alternatively, current TMS could be used for final picture, and option provided to import picture (made earlier) to use for initial map background.

**Comment by zdila** [comment]
For this I recommend to use some video editing tool and to post-process video generated by GPX animator. GPX Animator will not substitue it.
Hint: to get frame of the new map, specify its TMS URL andoutput as frame%06d.png. Then you can use generated PNG in video processing application.
