### ISSUE TITLE
Save the basic settings

### ISSUE THREAD

**Issue by charlysog** [zdila/gpx-animator#206]
Hello, I have been using GPX-Animator (1.5.2) for a few months now (my tours are based on "Komoot" based data) and the program works great for me up to a point where I have not yet found a solution. I cannot save the basic settings, so I have to re-enter my personal favorite settings every time I open the program. Under "Save" or "Save under" the error message appears every time: "Error saving configuration: null".
I would be very grateful for a useful tip.
(German translated with Google Translater)

**Comment by McPringle** [comment]
Sorry, but I have absolutely no idea what is causing this problem on your machine. On three of my machines, I was not able to reproduce this error. For the next version of GPX Animator, I modified the error message to show a complete track trace. With the stack trace, I'll get more information, and hopefully, I'll be able to reproduce your problem.

**Comment by McPringle** [comment]
Wie ich sehe, hast du automatisiert aus dem Deutschen übersetzt. Ich bin gebürtiger Deutscher, du kannst hier also auch auf Deutsch schreiben, wenn dir das leichter fällt.

Ich habe eine spezielle Version für dich erstellt, die schon eine neue Funktion aus v1.6 enthält. Kannst du es bitte mit der neuen Version ausprobieren? Im Fehlerfall solltest du nun nicht mehr nur eine kurze Meldung, sondern zusätzlich ein Textfeld mit dem so genannten Stacktrace sehen. Bitte kopiere den Stacktrace (es hat dort auch einen _Kopieren_ Button) und füge ihn hier als Kommentar hinzu. Er enthält Internas von der internen Verarbeitung, die mir hoffentlich helfen, das Problem einzugrenzen.

Die Version für dich habe ich dir auf meinem NAS zum Download bereit gelegt: https://mcpringle.duckdns.org/nextcloud/s/qGCFcTPN6aq4yCn

Wenn du Java 11 oder neuer installiert hast, kannst du die Datei direkt per Doppelklick starten.

**Comment by McPringle** [comment]
EN: I close this issue because there was no reaction within one month. If you still have a problem, please reopen this issue.

DE: Ich schließe dieses Thema ab, weil innerhalb eines Monats keine Reaktion erfolgt ist. Wenn du immer noch ein Problem hast, öffne bitte dieses Thema erneut.
