### ISSUE TITLE
Error While Rendering: Can't read logo: can't create an ImageInputStream

### ISSUE THREAD

**Issue by pinthenet** [zdila/gpx-animator#207]
GPX Animator 1.5.2
I successfully installed and ran GPX Animator last week and created several MP4s.
Today when I try to run it with the same settings (Track, Background Map, Forced Point Time interval etc) I get an 'Error While Rendering'. Map tiles are read successfully (OpenTopmap)

**Comment by McPringle** [comment]
Can you please save your settings (File > Save) and attach the saved file and the GPX file to this issue? If you want to keep your files private, you can send them via email to support@gps-animator.app (please refer to this task #207). If you use additional files like a logo for your animation, please provide it, too. This will help us to reproduce your problem and find a solution.

**Comment by pinthenet** [comment]
Unfortunately File/Save also doesn't work – same is issue https://github.com/zdila/gpx-animator/issues/206 I think.
I attach screenshots of the 2 tabs from my last successful  run, & the GPX (created as  KML in Google myMaps, converted to GPX online with GPS Visualiser).

Question: I tried to build the jar from GIT locally but gradlew assemble & run failed looking for Java 11 – I only have Java 8. Could that be the cause? Do I need to install the full JDK or just JRE?


![GPX Animator General settings](https://user-images.githubusercontent.com/3465407/91969698-cf3a7680-ed16-11ea-9626-f70c7d3f962d.jpg)
![GPX Animator Track settings](https://user-images.githubusercontent.com/3465407/91969701-cfd30d00-ed16-11ea-8e6d-13f9ebc24c00.jpg)
[full track.zip](https://github.com/zdila/gpx-animator/files/5161635/full.track.zip)

**Comment by pinthenet** [comment]
SOLVED!
In the settings shown the field 'Logo' is empty. In the current instance the value is set to **C:\Program Files\gpx-animator**
I changed this to **"C:\Program Files\gpx-animator"** and it works again. I can't explain how this field got changed

**Comment by McPringle** [comment]
Thank you very much for the update. I'll add a better error message in the next version.

**Comment by McPringle** [comment]
With #208 I created a new error dialog with a stack trace which will help a lot with error reports.

**Comment by pinthenet** [comment]
No problem, glad to help.

Actually, once I found it the warning was fairly logical. It just took me a while to see the logo field – what is it for anyway?

**Comment by McPringle** [comment]
You can specify a logo (a graphics file) that will be included in the animation in the top left corner. If you don't have a logo, you can use your profile picture instead, if you like.
