### ISSUE TITLE
Show speed

### ISSUE THREAD

**Issue by zdila** [zdila/gpx-animator#23]
Email report by Matt Makauskas:

> I just tried your and it is excellent! Thank you very much for sharing this project. I have not looked at the code yet, but I'm wondering if it is possible to label the tracks being drawn with the current speed (in mph or km/h, to two decimal places: ex: "56.75mph" or "94.62km/h"). Perhaps include a %SPEEDKMH% and %SPEEDMPH% ability when specifying the track label.

**Comment by McPringle** [comment]
The (optional) speed attribute was valid in GPX version 1.0 but removed from GPX version 1.1. The speed must be calculated manually between two GPS points based on the location. A TCX file still has the speed attribute, but this format must be supported, first (#38).
