### ISSUE TITLE
Keep Last Frame setting doesn't include the waypoints of the last frame

### ISSUE THREAD

**Issue by fwieringen** [zdila/gpx-animator#242]
I have a GPX file with three waypoints. The waypoints are shown througout the movie. When the movie reaches the end, the last frame will stick for 3 seconds, like I indicated in the settings. The waypoints disappear.

**Comment by McPringle** [comment]
Can you please provide a GPX file and the saved configuration (File > Save As) so I can reproduce the problem? If you don't want to post these files here on GitHub, you can send them via email to support@gpx-animator.add (please mention issue #242 in the mail).

**Comment by fwieringen** [comment]
Please find attached the GPX file.
[Fietstocht met waypoints.zip](https://github.com/zdila/gpx-animator/files/5588538/Fietstocht.met.waypoints.zip)

**Comment by McPringle** [comment]
The saved configuration:
[Fietstocht met waypoints.ga.xml.zip](https://github.com/zdila/gpx-animator/files/5588677/Fietstocht.met.waypoints.ga.xml.zip)

**Comment by McPringle** [comment]
I can confirm the problem: The waypoints disappear while `keepLastFrame` is rendered. I'll look into it.
