### ISSUE TITLE
Error when trying to save

### ISSUE THREAD

**Issue by fwieringen** [zdila/gpx-animator#243]
When I try to save a project, it gives an error message. See attached screenshot.
![Error](https://user-images.githubusercontent.com/4232879/100021052-21080f80-2de1-11eb-8a62-937bd83f6d07.png)

**Comment by McPringle** [comment]
Are you using windows and do you have more than one drive (e.g. C: and D:)?

I guess this error might be already fixed with commit 1fd78ba98272741309d022a44866ad41eab25f0b in the upcoming version 1.6 of GPX Animator.

**Comment by fwieringen** [comment]
True and true.

Sorry, didn't know that this was a known bug. Will wait for the update.

**Comment by McPringle** [comment]
No problem. I'll leave this issue open until the new release will be published and you can confirm that v1.6 solves your problem.

**Comment by McPringle** [comment]
I did a lot of testing to saving and loading files. This bug is fixed with v1.6, which should be available very soon. You can either build it yourself or wait a few days. Thank you very much for reporting this bug!
