### ISSUE TITLE
Photos are not included in video

### ISSUE THREAD

**Issue by Gelembjuk** [zdila/gpx-animator#244]
I have tried to use this app.
My GPX track is displayed fine.
But photos not. I have a folder with photos and selected this folder. 
Photos are jpeg and there are GPS EXIM info in photos
Example

`identify -verbose photo_155.jpg | grep GPS
    exif:GPSAltitude: 1933/1
    exif:GPSAltitudeRef: 0
    exif:GPSInfo: 107
    exif:GPSLatitude: 48/1, 7/1, 2515/100
    exif:GPSLatitudeRef: N
    exif:GPSLongitude: 24/1, 31/1, 5057/100
    exif:GPSLongitudeRef: E
    exif:GPSVersionID: 2, 2, 0, 0`

What can be wrong?  Is it possible to debug to find why?

I use gpx-animator on Ubuntu

**Comment by Gelembjuk** [comment]
I have found he reason.

phoos were ignored because there was no DATE_TIME_ORIGINAL Exif value.
If a photo has it, it will be included

Now i have some other problem, photos are added in wrong order. But i think it is still somethign with exif values in my photos

**Comment by McPringle** [comment]
Yes, we are using the timestamp of the photo. Not every camera has GPS but every (digital) camera stores the timestamp. The UI of adding photos is temporary, we will create a UI with better usability and photo validation in the future. Photos without a timestamp or a timestamp in the future (after the end time of the track) will be added at the end, IIRC.

If the photos are placed in the wrong order or the wrong position, it might be a timezone issue (different timezones used by GPX and photo device or you have photos from different camera with different timezone settings).
