### ISSUE TITLE
Where do I enter the OpenCycleMap API Key?

### ISSUE THREAD

**Issue by thomergil** [zdila/gpx-animator#248]
To prevent the "API Key Required" message, where do I enter my API Key? Thank you.

**Comment by thomergil** [comment]
The answer is to set this in the Background Map field:

`https://tile.thunderforest.com/cycle/{zoom}/{x}/{y}.png?apikey=API_KEY_GOES_HERE`

**Comment by McPringle** [comment]
Based on your experience, I added a FAQ entry to the [website](https://gpx-animator.app/#faq). (https://github.com/zdila/gpx-animator/commit/10c0a5a4f5a82807590874097c2934252d326eab)
