### ISSUE TITLE
Example command-line invocation fails

### ISSUE THREAD

**Issue by thomergil** [zdila/gpx-animator#249]
`java -jar build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input unified.gpx` fails.

The code seems to suggests that `--track-icon-file` and `--track-icon-mirror` are required. In addition, `--speed-unit` is required, but that option is not parsed by the code.

**Comment by McPringle** [comment]
You fixed it yourself with PR #250. Thank you very much for your contributions, great work!

**Comment by McPringle** [comment]
When adding new features, this error can occur again and again if the developer does not test the command line separately. To make this easier, I have added a first integration test that simulates the command line call:

`./gradlew integration`

This integration test is also run automatically before each push and takes about 12 seconds on my system. We had this problem more often in the past months, so it makes sense to automate this test.

See commit https://github.com/zdila/gpx-animator/commit/f68ef0e2d083d2c0d8663277acb2ae51b554f5b6
