### ISSUE TITLE
Predraw track should be a track setting, not a general setting

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#269]
Why? If you want to predraw a track, you might want to select different colors like you can select different colors for each track.

Important: This modification should be delivered with v1.6. If we first ship it as a general setting and move it to a track setting later, we'll get incompatible saved files and would have to handle this on every file load.

**Comment by McPringle** [comment]
Example: My bike tour from Lucerne to Barcelona and back. 20 days. In my video, I have added 20 tracks (one for each driving day) with a label ("Day 1" etc) and to make each day visually, with a different color. To make use of the pre-draw track feature, I would like to be able to choose a different pre-draw color for each day. For example track color blue, pre-draw color light blue; track color red, pre-draw color light red; etc.

**Comment by thomergil** [comment]
@McPringle, I agree. I hadn't thought of that. I will take a stab at this.

**Comment by McPringle** [comment]
I think I know an easy refactoring to do this.
