### ISSUE TITLE
Play a short sound when rendering finishes

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#275]
Some of my renderings took a really long time (high resolution, large tracks). Usually, I run them in the background and do some other work in parallel. It would be nice, to have a short sound at the end of the rendering for me to recognize, it has finished. One sound for a successful rendering, one sound for errors.

**Comment by zdila** [comment]
I think it should rather use OS notification system.

**Comment by McPringle** [comment]
That is a nice idea! There might be a library to do this system independent with Java.
