### ISSUE TITLE
The `--total-time` option does not work as expected, the video may be longer or shorter

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#287]
Example 1: `java -jar ./build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input .\src\test\resources\gpx\bikeride.gpx --output movie.mp4 --fps 30 --total-time 6000`
Result 1: Video length is 0:03 min (-3s)
Expected 1: Video length should be 0:06 min
Comment: The video was rendered with 97 frames. With 30 fps the video length is 0:03.2333 min.

Example 2: `java -jar ./build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input .\src\test\resources\gpx\bikeride.gpx --output movie.mp4 --fps 30 --total-time 60000`
Result 2: Video length is 1:02 min (+2s)
Expected 2: Video length should be 1:00 min
Comment: The video was rendered with 1'866 frames. With 30 fps the video length is 1:02.2 min.

Example 3: ` java -jar ./build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input .\src\test\resources\gpx\bikeride.gpx --output movie.mp4 --fps 30 --total-time 600000`
Result 3: Video length is 10:51 min (+51s)
Expected 3: Video length should be 10:00 min
Comment: The video was rendered with 19'559 frames. With 30 fps the video length is 10:51.9667 min.

As you can see, the difference is not always the same. The longer the video, the bigger the difference. It *might* have to do with calculations based on the `speedup` value and rounding differences, which grow over time.

**Comment by thomergil** [comment]
The most recent set of commits seem to have broken `--total-duration`. I just generated a movie with `--total-time 62835` and it became a movie of `Duration: 00:00:59.83`. When I revert back to `6ec5c2c64586b37276ca9c5c31068404fb1c888f` it correctly becomes a movie of `Duration: 00:01:02.83`.

**Comment by McPringle** [comment]
I'll check this out, thank you very much for the commit hash. Making things better can sometimes result in making things worse.

**Comment by thomergil** [comment]
Verschlimmbessern, as my mother would say. 😄

**Comment by thomergil** [comment]
I think the relevant diff is

```
-        speedup = cfg.getTotalTime() == null ? cfg.getSpeedup() : 1.0 * (maxTime - minTime) / cfg.getTotalTime();
-        final var frames = (int) ((maxTime + cfg.getTailDuration() - minTime) * cfg.getFps() / (MS * speedup));
         final var photos = new Photos(cfg.getPhotoDirectory());
+        speedup = cfg.getTotalTime() == null ? cfg.getSpeedup() : 1.0 * (maxTime - minTime) / getAnimationTime(photos);
+        final var frames = (int) ((maxTime + cfg.getTailDuration() - minTime) * cfg.getFps() / (MS * speedup));
```

**Comment by McPringle** [comment]
If I go back to `6ec5c2c64586b37276ca9c5c31068404fb1c888f` and run this command:

`java -jar ./build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input .\src\test\resources\gpx\bikeride.gpx --output movie.mp4 --fps 30 --total-time 6000`

The resulting video will have a length of 6.5 seconds, half a second too long. Now let's try it with 60 seconds:

`java -jar ./build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input .\src\test\resources\gpx\bikeride.gpx --output movie.mp4 --fps 30 --total-time 60000`

The resulting video will be 65 seconds long, which is 5 seconds too much.

When I try your example from slack:

`java -jar ./build/libs/gpx-animator-1.6.0-SNAPSHOT-all.jar --input .\src\test\resources\gpx\bikeride.gpx --output movie.mp4 --fps 30 --total-time 62835`

The video will be 68 seconds (exactly: 68.56) long.

Neither of the two variants calculates the speedup and/or the number of frames correctly.

**Comment by McPringle** [comment]
I guess I know the problem and have a solution. The problem:

The value for speedup was always calculated first, then the number of frames was calculated. Based on the high numbers and the complicated formula, there is a lot of room for rounding errors. This will end up in a small difference, which is growing by the hight of the values. In addition, there is an error that prevented drawing the last frame.

The solution:

When `--total-time` is not given (standard), use `--speedup` or the default speedup of 1'000, then calculate the number of frames based on the speedup value. In this case, ignore the values for `--tail-duration`, `--keep-last-frame` and `--photo-time` and `--photo-animation-duration`.

When `--total-time` is given, calculate the number of frames based on `--fps` or the default fps of 30, then calculate the speedup value based on the number of frames. In this case, the values for `--tail-duration`, `--keep-last-frame` and `--photo-time` and `--photo-animation-duration` need to be taken in advance (time for map animation vs. total video time).

I'll work on this issue today and check my findings and ideas.
