### ISSUE TITLE
internal error when parsing gpx.file

### ISSUE THREAD

**Issue by Lungko4711** [zdila/gpx-animator#293]
Was bedeutet die obige Fehlermeldung, die beim Rendern einer gpx Datei ausgegeben wurde und was ist zu tun?

**Comment by McPringle** [comment]
Dann ist ein Fehler aufgetreten, mit dem wir Entwickler vom GPX Animator nicht gerechnet haben. Welche Version von GPX Animator verwendest du? Heute ist Version 1.6 erschienen. Eine der Neuerungen ist, dass nicht nur ein Fehler angezeigt wird, sondern auch ein so genannter Stacktrace. Der gibt Auskunft über die Herkunft des Fehlers. Kannst du diesen bitte hier auch einfügen? Bei der Fehlermeldung gibt es extra dazu einen "Kopieren" Knopf.

Um den Fehler nachzuvollziehen ist es auch hilfreich, deine Daten zu bekommen. Zum Einen die GPX Datei und zum Anderen die Konfiguration von GPX Animator. Die kannst du mittels "Datei > Speichern" in eine Datei sichern. Beide Dateien kannst du hier im GitHub Issue hochladen. Wenn du das aus Datenschutzgründen nicht möchtest, kannst du diese Dateien auch per Mail an support@gpx-animator.app schicken. Schreibe im Betreff bitte "GitHub Issue #293", damit wir die Mail zuordnen können.

**Comment by thomergil** [comment]
@Lungko4711, can you share the .gpx file? If you don't want to publish it on the internet, maybe send it to @McPringle or to me. Thank you.

**Comment by Lungko4711** [comment]
This is the gpx.datei

Thank you for help.

_________________________________________________________________________


------ Originalnachricht ------
Von: "Thomer Gil" <notifications@github.com>
An: "zdila/gpx-animator" <gpx-animator@noreply.github.com>
Cc: "Lungko4711" <gurith@arcor.de>; "Mention" 
<mention@noreply.github.com>
Gesendet: 10.01.2021 13:52:09
Betreff: Re: [zdila/gpx-animator] internal error when parsing gpx.file 
(#293)

**Comment by McPringle** [comment]
Hallo @Lungko4711, da ist keine Datei -- weder an der Mail noch an diesem Ticket. Du musst die Datei entweder direkt hier in GitHub über deinen Browser hochladen (erfasse einen neuen Kommentar und klicke auf das symbolisierte Kettenglied: ![image](https://user-images.githubusercontent.com/1254039/104132584-9ecaaf00-537e-11eb-827a-0b052a35abe0.png)) oder schicke die Mail an support@gpx-animator.app. Wenn du eine Mail an GitHub schickst, kommt die Datei nicht an.

**Comment by McPringle** [comment]
Without a GPX file and GPX Animator configuration, I am not able to reproduce this error. I'm closing this issue now. If your problem is not solved and you can provide these files, you can reopen this issue.
