### ISSUE TITLE
Render a preview to quickly see video result

### ISSUE THREAD

**Issue by thomergil** [zdila/gpx-animator#294]
Sometimes I only want to see the first few seconds of a video to verify that it's doing the right thing. It would be nice to have a `--stop-after` flag that allows me (either in terms of frames or seconds) to abort video creation. That way, I can inspect the result of the video without having to wait a long time for the whole video to be generated.

I will probably do this today if you don't beat me to it.

**Comment by McPringle** [comment]
Today, you can achieve this using the trim feature. If your ride was going 60 minutes and you want to render the first 10, you have to trim 50 minutes of the GPX data: `--trim-gpx-end 3000000` (50 minutes * 60 seconds * 1000 ms).

A feature you are thinking of could be done inside the `CommandLineConfigurationFactory` only. If there is such a command line parameter, it can do the math and set `trimGpxEnd` automatically. So there does not need to be a change to the `Renderer` class.

**Comment by McPringle** [comment]
This is a preview feature. So I would call the command line parameter `--preview-length`.

**Comment by thomergil** [comment]
Excellent idea. I think this `--preview-length` should take an absolute number or a %.

**Comment by McPringle** [comment]
Tipp: I would take a look at the `Renderer` class, method `calculateSpeedupAndReturnFrames`. It calculates the speedup (which should not be altered) and the number of frames to render. Between lines 281 and 281, you should limit the number of frames to the value you calculate based on the new `--preview-length` parameter. With the already calculated number of `frames` together with `cfg.getFps()`, you have the length of the video. That should do the trick.

**Comment by McPringle** [comment]
The `calculateSpeedupAndReturnFrames` method has two returns, line 273 and 282. They should go to a variable and you can limit the number of frames after the `if` statement.

**Comment by thomergil** [comment]
Am I correct that the `--trim-*` features don't appear in `--help`?

**Comment by McPringle** [comment]
Yes, they are missing. They should be added to the help automatically. I'll investigate this issue.

**Comment by McPringle** [comment]
For now, I'll go with an easy implementation accepting the length of the preview video in ms. Can be easily extended later, if needed.
