### ISSUE TITLE
GPX vs gpx

### ISSUE THREAD

**Issue by krugerk** [zdila/gpx-animator#307]
Hello and thanks for sharing this tool.

A tool I used to export a route to gpx created a file the extension GPX. In turn, gpx-animator, using the "all supported formats" seemed to indicate none of the files in the chooser were supported. Toggling to "gpx files" resulted in the .GPX file being shown as selectable in the file chooser.

From a quick glance at the [source](https://github.com/zdila/gpx-animator/blob/b49e79edf7411bd72221a3329494f6e1bb3d8685/src/main/java/app/gpx_animator/ui/swing/TrackSettingsPanel.java#L379), when using the FileFilter, the accept method is performing a [string sensitive comparison ](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#endsWith(java.lang.String))of the end of the [filename](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#getName()) with "gpx". 

Host OS: macos
gpx-animator: Version 1.7.0-SNAPSHOT (recent master, Commit b49e79edf7411bd7)
java version: openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**Comment by McPringle** [comment]
Thank you very much for your report, I'll look into this issue.

**Comment by McPringle** [comment]
Foxed in v1.7.0 with backporting to v1.6.1

**Comment by krugerk** [comment]
Thanks for the quick fix. From the looks of it, the same sort of issue may appear when picking out png files although I did not experience that one first hand.

**Comment by McPringle** [comment]
You are absolutely right, thank you very much for pointing this out!
