### ISSUE TITLE
Replace Xuggler library

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#321]
Xuggler is no longer maintained and the use is deprecated. The last version 5.4, used by GPX Animator, is from 2012. We should check if we can move to a different library.

- [ ] remove dcm4che repository, too (used for Xuggler only)

**Comment by McPringle** [comment]
I tested [jcodec](http://jcodec.org/):

|          | Xuggler |   JCodec  |
|----------|:-------:|:---------:|
| Time     |    12 s |      49 s |
| Filezize |  586 KB | 12'033 KB |
| Quality  |   good  |    bad    |

For now, JCodec is not a suitable replacement for Xuggler.

**Comment by McPringle** [comment]
Take a look at https://github.com/artclarke/humble-video

**Comment by McPringle** [comment]
Today, I tested [Humble](https://github.com/artclarke/humble-video):

|          | Xuggler |   Humble  |
|----------|:-------:|:---------:|
| Render time     |    116 s |      208 s |
| Output filesize |  21'911 KB | 21'799 KB |
| Video quality  |   good  |    very good    |

Both solutions use FFmpeg behind the scenes. Humble is definitely slower than Xuggler but way better than JCodec. The file sizes are comparable, and the colors are indeed better with Humble. The modified code is in the branch `issue-321-humble`.

**Comment by McPringle** [comment]
I found a third project: [JavaCV](https://github.com/bytedeco/javacv)

**Comment by McPringle** [comment]
The issue with Humble video is tracked here: https://github.com/artclarke/humble-video/issues/112

**Comment by McPringle** [comment]
The issue (huge distribution file size) with JavaCV is fixed with 1.5.5-SNAPSHOT. I'll wait for the release of 1.5.5 to test it again with GPX Animator. See here: https://github.com/bytedeco/gradle-javacpp/issues/8

**Comment by saudet** [comment]
@McPringle It's been released! Please let me know if you encounter any other issues with either Gradle JavaCPP or JavaCV.

**Comment by McPringle** [comment]
@saudet Thank you very much for your work and for pinging me. I tried it with JavaCV 1.5.5. Maybe my configuration is wrong because the resulting Fat-JAR does only contain the Windows 64 Bit binaries (which is the system I ran the build on). My configuration looks like:

```
ext {
    javacppPlatform = 'linux-x86,linux-x86_64,macosx-x86_64,windows-x86,windows-x86_64'
}

dependencies {
    ...
    implementation 'org.bytedeco:javacv:1.5.5'
    implementation 'org.bytedeco:ffmpeg-platform:4.3.2-1.5.5'
    ...
}
```

I'm not sure if the problem is in front of my screen (misunderstanding of documentation) or if there is a new problem with JavaCV / JavaCPP ignoring the platform setting. A hint would be highly appreciated... :-)

**Comment by saudet** [comment]
You'll need to update as well the plugin to version 1.5.5 that fixes that bug:
>     id 'org.bytedeco.gradle-javacpp-platform' version '1.5.4'

**Comment by McPringle** [comment]
Oh, so stupid! Thank you very much, @saudet, to point me to my error. Now it works! But there is a crazy side effect: With v1.5.5 the video file is twice the size (521 KB vs. 1'113 KB) but looks like the same quality. I'll check the changelog if I may have to modify my `VideoFrameWriter` class, where I specify the codecs and quality.

**Comment by saudet** [comment]
If you need libx264, make sure to add "ffmpeg-gpl" instead of "ffmpeg".

**Comment by McPringle** [comment]
That was it! Now the size of the MP4 is exactly the same as before. I would never have thought of this change. Thank you very much for your help to replace Xuggler with JavaCV, @saudet!
