### ISSUE TITLE
Future release for Mac - question

### ISSUE THREAD

**Issue by albansuser** [zdila/gpx-animator#330]
Hello 

Having been using and enjoying the current release version for Mac, I was curious about the features of recent nightlies.

To my surprise the nighly compilation I tested will only run on Mac OSX 10.15.

Does this mean future releases will not be compatible with 10.13.6?

Thank you.

Regards

**Comment by McPringle** [comment]
Hi @albansuser, thanks for reaching out to us. What do you mean by nightlies? We do not do or publish nightly builds, just releases. Have you downloaded the source and build GPX Animator yourself?

It is probably just a misunderstanding. GPX Animator itself is written in Java, so it is independent of the operating system used. Java has a semi-annual release cycle. Currently, Java is at version 15.

The current version of GPX Animator requires Java 15 to run. Accordingly, GPX Animator has the same minimum requirements as Java 15:

- Linux: glibc version 2.12 or higher (x64)
- Windows: 2012r2 or later (x86/x64)
- macOS: 10.10 or later (x64)

So the version number 15 belongs to the Java version, not the macOS version. So yes, GPX Animator will also support macOS 10.13.6, at least in the near future. GPX Animator is also available as an installable version for Linux, Windows, and macOS. The installer has its own system requirements:

- Linux: all POSIX compatible systems
- Windows: 2012 or later, 7 or later (x86/x64)
- macOS 10.11 or later

Again, you should have no problem with your macOS 10.13.6.

Have fun with GPX Animator!
