### ISSUE TITLE
Add Photos

### ISSUE THREAD

**Issue by SilkSmooth** [zdila/gpx-animator#332]
I am trying to add photos, but no matter what I do, they are not showing up in the film.
I checked if the pic and the gpu had data info and they both have details.
There is no error no nothing,  what am I doing wrong?

**Comment by McPringle** [comment]
GPX Animator uses the timestamp of the photos to display the photos at the right spot in the animation. Your photos need the have correct timestamps. All more or less modern cameras are adding such a timestamp to the photo metadata. But to do this, the date, time, and timezone settings on your camera need to be set correctly. Same for the device where you record your GPX data. If one or both of the devices have incorrect dates, times, or timezones, the photos can't be added to the animation. This is the most common error.

If you provide me the files, I can try to reproduce your problem. I need the settings for GPX Animator (Menu "File" > "Save as"), the GPX file, and at least one photo. You can attach the files here on this issue. If you want to keep your files private, you can upload them to a private space, where I am the only one with access to: https://mcpringle.duckdns.org/nextcloud/s/7dDCzQ9a9eMj2kz

Alternatively, send these files via email to support@gpx-animator.app and mention this issue in the subject (issue 332).

**Comment by McPringle** [comment]
Message by email, the problem is solved:

> I tried it yesterday again, after I deleted all data and downloaded everything brand new (pics and gpx file) and it worked. 
> It seems like there was an issue with the gpx file, even though it stated all the dates and time
