### ISSUE TITLE
Rotate portrait photos to be displayed correctly

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#333]
From YouTube comment: https://www.youtube.com/watch?v=5b7kQv65dOE&lc=UgxzxeItu64RN5xcTzZ4AaABAg

**Comment by McPringle** [comment]
Looks like this is already done by `ImageIO.read`. In my tests with portrait photos shot with an android phone (Nokia 8.1 with Android 11) the photo was displayed correctly. So I'll close this issue without any modification.

**Comment by herrwusel** [comment]
I still have some issues where the photos were taken with gcam:
```bash
$ identify -verbose PXL_20210808_082630340.jpg | grep Orientation
  Orientation: TopLeft
```
The orientation isn't part of the exif data.
