### ISSUE TITLE
GPXAnimator reacting very slowly

### ISSUE THREAD

**Issue by hawosc** [zdila/gpx-animator#342]
Starting GPXAnimator takes at least half a minute. When I press the "Add Track" button it takes several minutes until the file dialog appears. My system: Windows 10 Pro 64.

Regards
hawosc

**Comment by McPringle** [comment]
Hi @hawosc 

On my system, which is Windows 10 pro 64 bit, too, the start of GPX Animator takes about 1.5 seconds. Opening the file dialog to add a track takes only a few milliseconds.

Can you please measure the exact time (so I can check the relation to a timeout) and check your network? How long does it take for the File Explorer to open?

Do you use the JAR file or have you used the installer? The installer creates a wrapper that checks for a new version on every start. The version check is done by loading the update information from https://download.gpx-animator.app/updates.xml

If the request to the file on the server fails, windows has a network timeout of 30 seconds. Same with opening the file dialog. If you have a network attached drive like a NAS, you can have the same problem. If it is not reachable, Windows blocks the process until it ran in the timeout.

My suggestion is: Reboot your system and check your network.

**Comment by hawosc** [comment]
Hi McPringle,

starting GPXAnimator takes about 26 sec, opening the file dialog for adding a track takes 58 sec, changing a directory in the file dialog box takes 17 sec.

Opening my file explorer takes under 1 sec. My network is working good. I also started GPXAnimator directly via command line, same result. I also updated my Java environment.

Regards
hawosc

**Comment by hawosc** [comment]
Hi McPringle,

I installed GPXAnimator on my notebook, it's a two year old workstation, and there GPXAnimator works fine. My PC is not the newest one, it has a 11 years old CPU AMD Phenom II, but for my purposes it works fine. Is there any CPU specific code that slows down my PC?

Regards
hawosc

**Comment by McPringle** [comment]
Hi @hawosc, sorry for my late answer, I am on easter vacation.

There is CPU specific code for the video codec. All versions up to v1.6.1 are using the Xuggler library for video encoding, since v1.7 (which is still in development) we are using JavaCV. Both libraries are based on FFmpeg. They have nothing to do with the start time or with file dialogs.

But you can try and clone this repo:

```
$> git clone https://github.com/zdila/gpx-animator.git
$> cd gpx-animator
$> ./gradlew assemble
```

This will clone the actual state of the repo with version 1.7.0-SNAPSHOT and build it. After the build has finished, please try running this test with Java 15:

```
$> java --enable-preview -ea -jar ./build/libs/gpx-animator-1.7.0-SNAPSHOT-all.jar --input ./src/test/resources/gpx/bikeride.gpx --output test.mp4
```

This will use a test GPX file and create a short animation. On my system (Intel i7-10700 / 8 cores / 64 GB RAM / RTX 2070) this takes 16 seconds. The resulting file has 534'180 bytes and the animation is 42 seconds long.

Then try to start the GUI via your command line and check how GPX ANimator behaves:

```
$> java --enable-preview -ea -jar ./build/libs/gpx-animator-1.7.0-SNAPSHOT-all.jar
```

Happy easter
Marcus

**Comment by hawosc** [comment]
Hi Marcus,

 

thank you for your detailed answer, I will try your suggestions next week.

 

Happy easter to you too.

hawosc

 

 

Von: Marcus Fihlon ***@***.*** 
Gesendet: Montag, 29. März 2021 20:07
An: zdila/gpx-animator
Cc: hawosc; Mention
Betreff: Re: [zdila/gpx-animator] GPXAnimator reacting very slowly (#342)

 

Hi @hawosc <https://github.com/hawosc> , sorry for my late answer, I am on easter vacation.

There is CPU specific code for the video codec. All versions up to v1.6.1 are using the Xuggler library for video encoding, since v1.7 (which is still in development) we are using JavaCV. Both libraries are based on FFmpeg. They have nothing to do with the start time or with file dialogs.

But you can try and clone this repo:

$> git clone https://github.com/zdila/gpx-animator.git
$> cd gpx-animator
$> ./gradlew assemble

This will clone the actual state of the repo with version 1.7.0-SNAPSHOT and build it. After the build has finished, please try running this test with Java 15:

$> java --enable-preview -ea -jar ./build/libs/gpx-animator-1.7.0-SNAPSHOT-all.jar --input ./src/test/resources/gpx/bikeride.gpx --output test.mp4

This will use a test GPX file and create a short animation. On my system (Intel i7-10700 / 8 cores / 64 GB RAM / RTX 2070) this takes 16 seconds. The resulting file has 534'180 bytes and the animation is 42 seconds long.

Then try to start the GUI via your command line and check how GPX ANimator behaves:

$> java --enable-preview -ea -jar ./build/libs/gpx-animator-1.7.0-SNAPSHOT-all.jar

Happy easter
Marcus

**Comment by McPringle** [comment]
I'll close this issue now because there was no action for about a month. If you still have the same problem, please check out my post above and reopen this issue, if necessary.
