### ISSUE TITLE
GUI won't start

### ISSUE THREAD

**Issue by MattUKSBS** [zdila/gpx-animator#347]
I can't start the GUI. The splash screen just sits there.
v1.5 used to work last year on my Win 10 64 bit PC but wouldn't start just now like this. 
Upgraded to the latest version (1.6.1) but still the same.

**Comment by McPringle** [comment]
Please try to start GPX Animator from the command line:

- Go to your install directory: `cd "C:\Program Files\gpx-animator" 
- Check Java version: `.\jre\bin\java.exe -version`
- Run GPX Animator: `.\jre\bin\java.exe --enable-preview -ea -jar gpx-animator-1.6.1-all.jar`

Does it start? If not, do you get any message on the command line?

**Comment by MattUKSBS** [comment]
Ignore me. It just took an age to start up. I went away from the PC for a couple of hours and when I came back the UI was there. So I estimate it took between 15 minutes and 2 hours to start.

**Comment by MattUKSBS** [comment]
I just timed it. The UI took 16 minutes to start. I have a decent spec PC but guessing something is up with it!

**Comment by McPringle** [comment]
You can try it on the command line like I have shown above and check if it starts faster or not. On my two-year-old notebook with Windows 10 64 Bit, GPX Animator takes about one second to start in GUI mode. Even on a slow PC, it should only take a couple of seconds to show the GUI.

**Comment by MattUKSBS** [comment]
File explorer is screwed on my PC. I have turned off indexing and GPX animator is now usable.
