### ISSUE TITLE
disable tail color fadeout on request

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#351]
After the route was animated, there are additional frames to fade out the tail color (`--tail-duration` together with `--speedup`). The new option `--tail-color-fadeout` takes a boolean (default `true`), where `true` is the default behaviour and `false` disables the fadeout.

see https://github.com/zdila/gpx-animator/issues/346#issuecomment-827428436

**Comment by piiskop** [comment]
It isn't about disablint the color fadeout at all. It's about being able to tell the program that once the track is done please stop the video, too, wherever it is with the fading currently.
