### ISSUE TITLE
No moving map (macOS 10.15.7)

### ISSUE THREAD

**Issue by rneppi** [zdila/gpx-animator#354]
How I get moving maps? I adjusted map-zoom-level at 15. Then only a fix map-section is displayed in movie an the track-line moves into and out of this section, but no map is moving.

**Comment by McPringle** [comment]
To get a moving map, the map must be bigger than the size of the video. If you like zoom level 15, go with it and set the visible width and height to the size you want your video to be (e.g. 1920x1080). Depending on the area of your travel, the map might be bigger than 1920x1080 and in that case, GPX Animator will create a moving map effect.

**Comment by rneppi** [comment]
Sorry, I don't get it. 
Where I define the size of the map? With the 4 fields of coordinates? 
Could you give an example please and/or a screenshot of the settings?

**Comment by rneppi** [comment]
Today I got it. And it works fine!
The reason was a GPX-file, wich contained an empty Track. This problem is described here: #366
