### ISSUE TITLE
Add option "freeze frame at beginning"

### ISSUE THREAD

**Issue by rneppi** [zdila/gpx-animator#355]
There is an option "freeze frame at end". Also at beginning some freezed frames are in several cases (f.i. some stuff for cutting) usefull.

Workaround till then: Insert a trackpoint before the first one and set the timestamp some minutes (according to your other adjustments) before the first trackpoint. So you get some "freezed" frames.

**Comment by McPringle** [comment]
Nice idea. That is really easy to implement, too.
