### ISSUE TITLE
Panorama Fotos

### ISSUE THREAD

**Issue by rneppi** [zdila/gpx-animator#356]
It would be great if bigger fotos such as panoramas are fitted so that they are not cropped.

Even better would be, that movies could be insertet as fotos, f.i. to display a pan shot of a large panorma. But that was already said in #352.

**Comment by rneppi** [comment]
Hi,

attached you get the zipped files. Additionally it contains the genereated mp4-file so you can see, what I mean.

Regards 
Rainer

**Comment by McPringle** [comment]
Hi Rainer, sending an email with an attachment to GitHub does not work. GitHub ignores attachments from emails. Either you must upload it directly to GitHub using your browser or you must send it to our support mail support@gpx-animator.app.

**Comment by McPringle** [comment]
I got your email and will investigate your problem. Thank you very much for sharing your data, that will help me reproducing your issue.

**Comment by McPringle** [comment]
With GPX Animator v1.7, it works as expected. I fixed the calculation of the photo size for vertical videos with issue #302, which fixed this case, too. Please wait for the next release of GPX Animator (I can't tell you a release date yet, _maybe_ September). Thank you very much for reporting, this is very helpful in catching as many bugs as possible…

**Comment by rneppi** [comment]
Nice to read!
