### ISSUE TITLE
wrong path

### ISSUE THREAD

**Issue by rneppi** [zdila/gpx-animator#359]
After saving and reopening a profile on an iMac running MacOs 10.15.7, the links for output and GPX-files are wrong and look like this:
Before saving:
`/Users/<name>/Desktop/<folder>/<track.gpx>`
after saving and reopening: 
`/Users/<name>/<folder>/GPX Animator Konfigurationen/../../Desktop/<folder>/<track.gpx>`

Always only 1 slash! I dont't know, why here 2 or more are displayed.

**Comment by McPringle** [comment]
I can reproduce the problem on my MacBook, thanks for reporting it.
