### ISSUE TITLE
Add a profile picture

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#36]
I would like to add a profile picture to the rendered video showing a picture of the person who did the bicycle trip or the hiking tour. E.g. at the top left corner.

**Comment by zdila** [comment]
I think this should be done in video editor where you can do lot more and the way you want. GPX animator should only focus on generating animation from GPS files.

**Comment by McPringle** [comment]
What do you think about a plugin mechanism like ffmpeg uses?

**Comment by zdila** [comment]
I like the idea that gpx animator would be a plugin for ffmpg :-)
