### ISSUE TITLE
Term issue

### ISSUE THREAD

**Issue by rneppi** [zdila/gpx-animator#363]
Because GPX-Animator operates with tracks and not with routes, tabs and button „Route hinzufügen“ and „Route löschen“ f.i. should be renamed as this (German translation only?).

**Comment by McPringle** [comment]
Do you have a better suggestion? "Track" translates to "Spur" or "Fährte", which sounds awkward…

**Comment by rneppi** [comment]
Please call it in following way:
"Route hinzufügen" -> "Track hinzufügen" and
"Route löschen" -> "Track löschen"
That should be clear and not confuse with "Route" in terms of GPX-definition.
"Spur" would no problem for me too, but who is handling GPX-Files can handle the Anglicism "Track" and "Route", I would say.  "Track" and "Route" are basic-terms relating to GPX in German language as well, I think.

**Comment by McPringle** [comment]
Okay, you convinced me. I'll change the translations. :-)
