### ISSUE TITLE
Suggestion for improvement: Handling of GPX-files containing waypoints only

### ISSUE THREAD

**Issue by rneppi** [zdila/gpx-animator#364]
At this moment it is necessary to add GPX-files containing a track, optionally waypoints. The user can add more GPX-files. Isn’t it possible too, to add GPX-files containing only waypoints? If this, the waypoints could appear in the timeline managed by their timestamps and with an own Symbol assigned in their tabs in the same way as tracks. May be definitions in common-tab for waypoints become redundant and are not necessary any more.

**Comment by McPringle** [comment]
Thank you very much for posting your improvement. But this is not what a waypoint stands for. Waypoints are just points in the map and are not related to a track. GPX Animator was build to animate recorded tracks. Rendering a file without a track does not make any sense.

From [Wikipedia](https://en.wikipedia.org/wiki/GPS_Exchange_Format#Data_types):

> - **wptType** is an individual waypoint among a collection of points _with no sequential relationship_. It consists of the WGS 84 (GPS) coordinates of a point and possibly other descriptive information.
> - **rteType** is a route, an ordered list of routepoint (waypoints representing a series of significant turn or stage points) _leading to a destination_.
> - **trkType** is a track, made of at least one segment containing waypoints, that is, _an ordered list of points describing a path_. A Track Segment holds a list of Track Points which are logically connected in order. To represent a single GPS track where GPS reception was lost, or the GPS receiver was turned off, start a new Track Segment for each continuous span of track data.

I have highlighted the relevant aspects in italics.

**Comment by rneppi** [comment]
"Rendering a file without a track does not make any sense." – May be you misunderstood me. I think it makes absolutely sense. GPX-animator handles multiple GPX-files containing tracks and waypoints. Why should it not handle GPX-files containing only one kind of content too? Containing only tracks works already. And GPX-Files can not only generated by hardware. You can make them by software (like [routeconverter.de](https://routeconverter.de)). If you have an GPX-file only with waypoints and timestamps, you could use it together with GPX-Animator to make a movie too:

- I would do that in that case, if I wont to display at first a sequence of locations initially without a track (f.i. main locations where the track will pass later) before an animated track is displayed. In this moment for that I have to edit the GPX-file (wich contains the track) adding the waypoints. To do this in different files is clearly, especially if you have more than one track in more than one GPX-file. 
- If I have several categories of Waypoints, different symbols can be assigned to each categorie, but only if the waypoints are in different files.
- An other example where processing of only-waypoint-GPX-files is usefully, is if you use it as a "control file". You can control the timeline f.i. I would use this to place in the movie small symbols as markers. After generating track-movie with GPX-Animator, in a movie-cut-app I find the markers at the specified time and can do at this positions some actions, wich are not possible with GPX-Animator.

**Comment by McPringle** [comment]
GPX Animator was build to render tracks as animations. What should GPX Animator do with a GPX file containing only waypoints? If the waypoints have time information, it might be possible to create an animation. But it will be a lot of work because the process of examining the map area, timing, etc. is based on tracks. 

Probably the whole calculation process has to be rewritten or even rewritten from scratch. I don't see any added value in this, so personally, my time is too precious for this (GPX Animator is purely a spare time project). But I don't mind someone else doing this and contributing to it. You're more than welcome to do so if you'd like. Then we can reopen this issue as well.
