### ISSUE TITLE
Suggestion for improvement: Selecting attributes from GPX-File

### ISSUE THREAD

**Issue by rneppi** [zdila/gpx-animator#365]
It would be great, if there where the possibility, where the user could select in track-tab which "text"-attribut-tag (<name>, <desc>, <src>, <ele> … or a combination of them, if possible) is displayed beside a (track- or) waypoint in movie. Also displaying attribut-text should be detachable, so only a symbol is displayed. 
(The feature is especially usefull together with waypoints, not so much with trackpoints but may be sometimes.)

**Comment by McPringle** [comment]
A track point in a GPX file usually only contains the GPS coordinates (latitude and longitude) and optionally the elevation and/or time. Some GPS devices record additional data from paired sensors like temperature, heart rate, speed, cadence, etc. I have never seen a GPX file where the track points contain additional text attributes or properties, except the comment (which is already displayed in the animation). So I don't know which additional text attribute could be displayed…

**Comment by rneppi** [comment]
My suggestion especially points at waypoints. If attributes are given to only some tracks (because of clarity display), this could be relevant in the same way.

Please don't forget that GPX-files are not only generated by hardware. With software user can define some additionally attributes. (Sometimes I generate a track with my favorite GPX-software by setting  prominent way- or track-points, converting them into a route, let the software find the route by a service, and convert this back into a track with all necessary trackpoints. Refinement could be usefull. After this I (can) add  timestamps and attributes at main points.)

Possible attributes are listet here: [http://www.topografix.com/GPX/1/1/](http://www.topografix.com/GPX/1/1/)

For example possible "text"-atribute-tags could be: lat, lon, ele, time, name, cmt, desc, src, link. (In my first comment above they are not shown, sorry.) – Wich attribute plotts GPX-Animator at this time, cmt?
