### ISSUE TITLE
Support direct YouTube upload

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#39]

**Comment by zdila** [comment]
I like unix philosophy that one tool shoul do one function and do it good. YouTube upload is easily scriptable and it can use output of GPX animator.

**Comment by thomergil** [comment]
As commented in https://github.com/zdila/gpx-animator/issues/40, I think this is feature creep.

**Comment by McPringle** [comment]
You have convinced me, I will close this issue.
