### ISSUE TITLE
How to add a custom map

### ISSUE THREAD

**Issue by ventoux84** [zdila/gpx-animator#394]
I would like to put in background a map from IGN which requires this type of url :
https://wxs.ign.fr/CLEF/inspire/r/wms? LAYERS=OI.OrthoimageCoverage&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=&CRS=EPSG:4326&BBOX=47.34956960,3.25167353,47.38545104,3.30486151&WIDTH=256&HEIGHT=256

But I don't know, in a command line, how to give BBOX, WIDTH, and HEIGHT as parameter. 
Is it possible ? Thank you for any information on this subject.

EDIT : IGN also offers vectors tiles  tms with the standard .pbf.
 https://wxs.ign.fr/essentiels/geoportail/tms/1.0.0/PLAN.IGN/{z}/{x}/{y}.pbf
This does not work either, perhaps because of vector instead of raster and .pbf instead of .png.

**Comment by ventoux84** [comment]
It works with this url, using wmts
'https://wxs.ign.fr/pratique/geoportail/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&EXCEPTIONS=text/xml&FORMAT=image/png&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&&TILEMATRIX={zoom}&TileCol={x}&TileRow={y}'

**Comment by pedjas** [comment]
Where is maps.xml located in Windows?

**Comment by ventoux84** [comment]
The same that Linux, in a hidden folder at the root of the user's folder.

**Comment by McPringle** [comment]
GPX Animator has no own map database. That was too much work to keep up to date. GPX Animator uses the map database from [JOSM](https://josm.openstreetmap.de/). New maps should be added there, so they are available not only to GPX Animator but to other tools as well: https://josm.openstreetmap.de/wiki/Maps

**Comment by pedjas** [comment]
It would be useful if there is option to set custom map. It's mainly just setting up custom URL to map tiles.
