### ISSUE TITLE
Where can I find the URL's for --tms-url-template?

### ISSUE THREAD

**Issue by therealrobster** [zdila/gpx-animator#397]
Hi all,

I'm loving this software!  Have made up a bash script to process the GPX file/s in a folder.

However, the example shows `--tms-url-template 'https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={zoom}'`

I want to use openstreetmaps and a particular map in the list that the GUI shows.   

Where can I get a list of these URL's so I can enter the one I want?

Thank you so much.

**Comment by ventoux84** [comment]
user/.gpx-animator/maps.xml

**Comment by therealrobster** [comment]
Thank you but I can't find any file called maps.xml on my whole home folder, let alone in the ....

Hold up, hidden folder...  go it!  Thank you

It'd be great if this was in the docs, just as a help for new users.  I very much appreciate your pointing me to this file.

For anyone in the future it's in (linux):
`/home/yourUserName/.gpx-animator/maps.xml`

Not sure about windows / mac
