### ISSUE TITLE
Support direct Vimeo upload

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#40]

**Comment by zdila** [comment]
I like unix philosophy that one tool shoul do one function and do it good. Vimeo upload is easily scriptable and it can use output of GPX animator.

**Comment by thomergil** [comment]
@McPringle, it's a cute idea, but I think this is feature creep. I agree with @zdila: stick with the UNIX philosophy of small tools that do simple things. I would suggest closing this issue.

**Comment by McPringle** [comment]
You have convinced me, I will close this issue.
