### ISSUE TITLE
World: Bing aerial imagery not working

### ISSUE THREAD

**Issue by zackdvd** [zdila/gpx-animator#400]
Hi, quick comment, I get an error if I want to use World: Bing aerial imagery as background map.
could not get tile https://www.bing.com/maps/

Version 1.7.0, just downloaded, first time user. Other backgrounds work. 

Anyway: Thanks for that great tool!

**Comment by StefanGebhardt** [comment]
Same problem for me; 1.7.0 on MacOS

**Comment by McPringle** [comment]
Duplicate of #391
