### ISSUE TITLE
New Feature: Offline Support

### ISSUE THREAD

**Issue by HanSolo68** [zdila/gpx-animator#402]
It would be great to have a solution during travels to get (at least) one map type in one scaling locally. This could be via cache (which has to be filled before the travel), a local map tiler or whatever.

**Comment by HanSolo68** [comment]
A local map tiler could be: https://www.maptiler.com/server/

But I would need help in using it together with GPX Animator

**Comment by McPringle** [comment]
Offline support for GPX Animator sounds good but is terrible to implement. There are 16 to 20 zoom levels with thousands to a few hundred thousand tiles. You need a way to specify the area and wanted zoom levels for the download, which might be several GBs very quickly. If you try to render something with a different zoom level or outside the pre-downloaded area, or with some different setting like visible area or moving map, it will crash.

If you don't want to connect to the internet, I'll recommend using a local map tile server like the one you mentioned. Running it as a Docker image should be easygoing. To use it together with GPX Animator, just add the URL with placeholders to the background map field, e.g. http://localhost:3650/path/{zoom}/{x}/{y}.png
