### ISSUE TITLE
New Feature: Skip Long Stays When Data Are Missing

### ISSUE THREAD

**Issue by HanSolo68** [zdila/gpx-animator#404]
Following scenario:
Weekend trip Fri to Sun
Travel on Friday and back on Sunday
Hiking on Saturday

I want to create separate GPX videos for the travel and hiking (The later is no problem).

When adding the GPX files from Friday and Sunday, I get lot of video for Saturday, where nothing happen (except updating the time).

There should be an option to skip the missing data (maybe with such a flash you already have implemented).

**Comment by McPringle** [comment]
As I understand you, you have two GPX files. If you add two GPX files to GPX Animator which do not overlap, this should work already. Just activate "Skip Idle" and render the video. You will see a flashback effect between the two files. You can configure this effect using the "Flashback Color" and "Flashback Duration" options.

An example is online here on YouTube: https://www.youtube.com/watch?v=SnN0tsyqRN8

I rendered the video using 20 GPX files of 20 different dates. Between each date, you can see the flashback effect. If this does not solve your problem I misunderstand your requirement, please reopen this issue.
