### ISSUE TITLE
Customizing displayed information

### ISSUE THREAD

**Issue by pedjas** [zdila/gpx-animator#409]
It seems we have options to set if information of track point is displayed and where, but it always displays all information.

It would be great to have an option to choose what information is displayed. For example, sometimes it is needed to have just time, not speed and coordinates.

**Comment by McPringle** [comment]
That was already implemented with #156 and will be available in v1.8.

**Comment by robinalexandre** [comment]
Hello,

Thank you for this app.
When using the CLI with --information, we got : 16:38:45.736 [main] ERROR app.gpx_animator.Main - Missing implementation of command line option 'INFORMATION'. Please report to support.


It seems that the information parameter has been set only for GUI.
