### ISSUE TITLE
Error in Bounding Box Calculation with HD video size

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#41]
Width: 1920
Height: 1080
no bounding box specification

Result: The map in the video is kind of "zoomed in", it displays only a part of the track. Please take a look at the attached ZIP file containing all neccessary data:

- FullHDTest.ga.xml (saved settings of GPX Animator)
- Regenfahrt.gpx (the recorded GPX data)
- Regenfahrt.mp4 (the resulting HD video)

If I omit the witdth and the height of the output video, the track is displayed correctly (completely). But it is not HD, in my case it is some kind of "portrait mode" which I don't like and some players have problems with.

[testdata.zip](https://github.com/zdila/gpx-animator/files/2707137/testdata.zip)

**Comment by n76** [comment]
A work around is to specify the zoom parameter in addition to the width and height. Unfortunately it seems getting the correct zoom (one that fully shows the track in the desired aspect ratio) seems to be a trial and error process.

It would be better if a reasonable zoom value were automatically selected where the whole track is shown when the user enters both height and width.
