### ISSUE TITLE
Total time field seems disabled

### ISSUE THREAD

**Issue by thereticle** [zdila/gpx-animator#410]
Hi,
thank you for the very useful app.
The 'total time' field seems to be disabled, in fact no data can be entered.
GPX Animator v 1.7.0

![immagine](https://user-images.githubusercontent.com/20416601/177117353-3329ca05-72a2-423c-abeb-fbe8753c25f2.png)

**Comment by McPringle** [comment]
You have set a "Speedup" of "1000". If the speedup value is present, the total time of the video will be calculated based on the speedup. If you remove the speedup value, the total time field will be enabled. You either set the speedup or the total time, not both. They are mutually exclusive. Empty the speedup field should solve your problem. If not, please reopen this issue. :-)
