### ISSUE TITLE
Exif orientation information of pictures is not used

### ISSUE THREAD

**Issue by wasinix** [zdila/gpx-animator#417]
When using pictures in gpx-animator (tested with version 1.7.0) that are taking upside down and have set the according exif orientation value to "bottom-right", this is not respected at video generation and the picture is shown rotated by 180°.

Attached an example picture, that is shown correct in all imagetools I tried, but is rotated upside down, when used for gpx-animator.

![GOPR0701](https://user-images.githubusercontent.com/11388794/185785575-c9cdc0c5-d2e5-49de-874b-371dc747e4c6.JPG)
![image](https://user-images.githubusercontent.com/11388794/185785995-601305bc-1b8c-4bcf-8db0-74c35529a14a.png)

**Comment by McPringle** [comment]
Thanks to @scordio at the Hackergarten Luzern we fixed this bug. On my Nextcloud instance you can download a JAR file to test the fix (it was too big to attach it to this issue):

https://kdrive.infomaniak.com/app/share/333065/e0be0ff9-6207-4a7e-959b-0d6b2f2d1ee4

We would like to hear back from you if this fix solves your photo issue. Thank you very much for reporting and providing an example!

**Comment by wasinix** [comment]
Hi @McPringle, I gave your test version a try and the picture orientation problem is fixed for me with this version.
Thanks for taking care about this issue and thanks to @scordio too!
