### ISSUE TITLE
Possibility to use other maps

### ISSUE THREAD

**Issue by DGrv** [zdila/gpx-animator#53]
Is it possible to use other maps ?

Example : 
* Hillshading [http://c.tiles.wmflabs.org/hillshading/{2}/{0}/{1}.png](http://c.tiles.wmflabs.org/hillshading/%7B2%7D/%7B0%7D/%7B1%7D.png)
* Austria Topographie [https://w{3}.outdooractive.com/map/v1/raster/topo_bev/{2}/{0}/{1}/t.png?project=alpenverein](https://w%7B3%7D.outdooractive.com/map/v1/raster/topo_bev/%7B2%7D/%7B0%7D/%7B1%7D/t.png?project=alpenverein)
* SwissTopo ([Geoadmin](https://map.geo.admin.ch)) which have incredible maps and data [https://w{3}.outdooractive.com/map/v1/raster/topo_swisstopo/{2}/{0}/{1}/t.png?project=alpenverein](https://w%7B3%7D.outdooractive.com/map/v1/raster/topo_swisstopo/%7B2%7D/%7B0%7D/%7B1%7D/t.png?project=alpenverein)
  - Example used by a swiss website for skitouring or hiking, combining all layers usefull https://www.gipfelbuch.ch/gipfelbuch/detail/id/98104/Alpine_Wanderung/Morgenberghorn
* Slope from outdooractive [https://s{3}.outdooractive.com/map/xGradient/{2}/{0}/{1}.png?project=alpenverein](https://s%7B3%7D.outdooractive.com/map/xGradient/%7B2%7D/%7B0%7D/%7B1%7D.png?project=alpenverein)
* Kompass [http://ec{3}.cdn.ecmaps.de/WmsGateway.ashx.jpg?Experience=kompass&MapStyle=KOMPASS%20Touristik&TileX={0}&TileY={1}&ZoomLevel={2}](http://ec%7B3%7D.cdn.ecmaps.de/WmsGateway.ashx.jpg?Experience=kompass&MapStyle=KOMPASS%20Touristik&TileX=%7B0%7D&TileY=%7B1%7D&ZoomLevel=%7B2%7D)
* OenTopoMap [https://a.tile.opentopomap.org/{2}/{0}/{1}.png](https://a.tile.opentopomap.org/%7B2%7D/%7B0%7D/%7B1%7D.png)
* OpenCyclemap [http://a.tile.thunderforest.com/cycle/{2}/{0}/{1}.png](http://a.tile.thunderforest.com/cycle/%7B2%7D/%7B0%7D/%7B1%7D.png)

Thanks

**Comment by DGrv** [comment]
I actually found how to do. I add to read the comments when you have the mouse on the "background map" box. You can choose your own by using such links as I wrote above (using zoom, x and y).

PS: Great tool :)

**Comment by zdila** [comment]
Thanks. As you've found out how to do it I am closing it.
