### ISSUE TITLE
Add an image/icon to the actualposition

### ISSUE THREAD

**Issue by McPringle** [zdila/gpx-animator#54]
For example a bike icon, like in this animation:
https://youtu.be/BGJprFZ7VsM?t=14

**Comment by McPringle** [comment]
To make it easier to implement for the first step, we could just use an optional, configurable emoji which itself is not turning according to the direction of travel.

**Comment by n76** [comment]
If this is implemented, it would be nice if the direction of travel was run through a low pass filter to avoid all the flickering back and forth that is seen in the linked video. Consider it a "stretch goal". :)

**Comment by heroichornet** [comment]
> If this is implemented, it would be nice if the direction of travel was run through a low pass filter to avoid all the flickering back and forth that is seen in the linked video. Consider it a "stretch goal". :)

That flicker is making my head ache xD

**Comment by McPringle** [comment]
Today GPX Animator only supports 2D maps. A 2D Icon would be good enough. I don't think it will flicker. We'll see and can add more functionality later, if needed.

**Comment by heroichornet** [comment]
I'm working to make it configurable, not ready for a pull request

**Comment by McPringle** [comment]
Found a bug:

1. Start GPX Animator
2. Add a track (*Enable Icon* is clickable)
3. Save the configuration
4. Close GPX Animator
5. Start GPX Animator again
6. Load the saved configuration

Expected behavior: *Enable Icon* is clickable and can be changed.
Actual Behavior: *Enable Icon* is deactivated and can't be changed.

**Comment by heroichornet** [comment]
I'll take a look as soon as possible
