### ISSUE TITLE
text.ParseException: Unparseable date

### ISSUE THREAD

**Issue by sgofferj** [zdila/gpx-animator#6]
I tried several GPX files, either from Sportstracker or from my Garmin Geko (via GPSBabel) and I always get a message like this one:
java.text.ParseException: Unparseable date: "2013-04-14T16:57GMT:50.45"
I GREPped for "GMT" in the GPX file but it doesn't occur. The time stamps look ok to me.
Tested with 1.1 and 1.2.

System:
kubuntu 14.04
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by sgofferj** [comment]
Found a very old GPX file which worked. Time stamps in that look like this:
<time>2011-05-20T12:41:51Z</time>
However, time stamp in newer files and files from Sportstracker look like this:
<time>2014-05-23T17:21:08.98</time>

**Comment by zdila** [comment]
Fixed in 4071359cc11aaa6e6b23264187f72e82628b5552. Will be in next release.
