### ISSUE TITLE
Feature request: add Finnish map sources

### ISSUE THREAD

**Issue by sgofferj** [zdila/gpx-animator#7]
The Finnish Geographical Service has published all it's data under an Opendata license. Data is available via WMS and TMS URLs.

License:
http://www.maanmittauslaitos.fi/en/opendata/terms-of-use

Download server:
http://kartat.kapsi.fi/

WMS:
Basic map: http://tiles.kartat.kapsi.fi/peruskartta?
Topo map: http://tiles.kartat.kapsi.fi/taustakartta?
Aerial image: http://tiles.kartat.kapsi.fi/ortokuva?

**Comment by zdila** [comment]
You can add custom TMS URL template directly to `Background Map` text field, or specify it as `--tms-url-template` parameter. See Help/Usage for format details.

Predefined maps has been generated from http://josm.openstreetmap.de/maps. If your maps are OSM compatible then you can add your definition there and in further release it will get to GPX Animator.

**Comment by zdila** [comment]
Note that I've updated the default map sources in the version 1.2.3. But I don't know if your maps are included. If not, you can still specify it manually.
