### ISSUE TITLE
NPE when rendering map tile

### ISSUE THREAD

**Issue by zdila** [zdila/gpx-animator#76]
Mail report from Stefanelli Wolfgang <stefanelli.wolfgang@gmail.com>:

> Hi Martin
> 
> Thank you for the fast reply. Please find enclosed the log. First I rendered without map, it worked, then I tried Open Street Map (German Style), it didn’t work…
>
> Additional to that automatic boundary didn’t work as well, the track went outside the video. Is there something I need to consider when using that?
>
> Thank you
> Wolfgang

Error log: [Terminal GPX Animator.txt](https://github.com/zdila/gpx-animator/files/3292789/Terminal.GPX.Animator.txt)

Caused probably by `null` being returned at https://github.com/zdila/gpx-animator/blob/master/src/main/java/sk/freemap/gpxAnimator/Map.java#L80

**Comment by McPringle** [comment]
For the calculation of the video boundary, there is already a (slightly different) bug: https://github.com/zdila/gpx-animator/issues/41

**Comment by McPringle** [comment]
This is an HTTP to HTTPS forwarding issue:

```
HTTP/1.1 302 Found
Location: https://b.tile.openstreetmap.de/tiles/osmde/6/39/28.png
```
