### ISSUE TITLE
New map background wish

### ISSUE THREAD

**Issue by fidollus** [zdila/gpx-animator#89]
Would it be possible to add swisstopo (www.map.geo.admin.ch)?

THX
Fido

**Comment by McPringle** [comment]
That should be possible. We have to figure out licensing and API.

**Comment by fidollus** [comment]
Hi!
Thank you for your response. The API can be found here:
https://api3.geo.admin.ch/
Greetz
Fido
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 08/11/2019 - 11:48 (MN)
An : gpx-animator@noreply.github.com
Cc : soundnet@bluemail.ch, author@noreply.github.com
Betreff : Re: [zdila/gpx-animator] New map background wish (#89)
That should be possible. We have to figure out licensing and API.

**Comment by McPringle** [comment]
Thanks to issue #241, there will be three Swisstopo maps available with GPX Animator v1.7.
