### ISSUE TITLE
Allow specification of time zone

### ISSUE THREAD

**Issue by n76** [zdila/gpx-animator#90]
Issue: Recorded tracks while on vacation 9 time zones away. Now attempting to create animations gpx-animator is putting my local time on the video. Since I wasn't hiking in the middle of the night the time looks very wrong.

It would be very nice if you could specify the time zone the GPX track should be displayed in.

**Comment by heroichornet** [comment]
Wikipedia on GPS Exchange Format, time: https://en.wikipedia.org/wiki/GPS_Exchange_Format
> Dates and times are not local time, but instead are Coordinated Universal Time (UTC) using ISO 8601 format.[1]
=> Alll GPX time stamps are UTC+0

**Comment by heroichornet** [comment]
<img width="690" alt="Screenshot 2019-11-07 at 19 47 34" src="https://user-images.githubusercontent.com/1138612/68417884-81f18500-0197-11ea-88a4-84854495a795.png">

Field that does not accept negative values

**Comment by blackenstock** [comment]
this bug is for correcting wrong time information due to wrong time in the gps recorder. so the offset is a static offset - not changing when passing timezone borders.

**Comment by n76** [comment]
My issue is not that the UTM based time stamps in the GPX file are wrong.

It is that I recorded them while in Italy and then created the map animation while in California. gpx-animator is using my UTM-8 timezone to convert the time stamps to local time. In this case the video shows an early morning time instead of a late afternoon time. I'd prefer it to use UTC+1 timezone when generating the video.

Having the local timezone be the default is fine, but allowing the user to specify a different timezone for creating the displayed time would nice. In the meantime, I think if I add a `TZ=+01:00;export TZ` before starting gpx-animator I might have a work around.

**Comment by McPringle** [comment]
We should check the code and rewrite the date and time handling to use the Java Date and Time API, introduced with Java 8. That handles timezones and converting times between timezones out of the box. I know this API pretty well because I did a few talks at conferences about it.

**Comment by McPringle** [comment]
There is no need anymore to specify the timezone manually. With solving issue #91 this will be done automatically. If the time itself is not correct, it can be corrected after issue #10 is solved. That is the reason for this issue now.
